name: knightsbridge
services:
- name: knightsbridge-backend
  source_dir: /backend
  github:
    repo: williamdowning/knightsbridge
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    scope: RUN_AND_BUILD_TIME
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "8080"
    scope: RUN_AND_BUILD_TIME 